home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^trashes/', include('trashes.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

trashes/urls.py
from django.conf.urls import url

from . import views

app_name = 'trashes'
urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/$', views.create, name='create'),
    url(r'^update/(?P<id>\d+?)$', views.update, name='update'),
    url(r'^delete/(?P<id>\d+?)$', views.delete, name='delete'),
    url(r'^detail/(?P<id>\d+?)$', views.detail, name='detail'),
    url(r'^restore/(?P<id>\d+?)$', views.restore, name='restore'),
    url(r'^clear/(?P<id>\d+?)$', views.clear, name='clear'),
]

trashes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
from django.db import models


class Trash(models.Model):
    """model for trash."""

    trash_path = models.CharField(max_length=200, default=os.path.expanduser(
                                  "~/.local/share/my_trash"), unique=True)
    max_trash_size = models.IntegerField(default="100000")
    max_file_size = models.IntegerField(default="100")
    max_file_time = models.IntegerField(default="604800")
    free_space = models.IntegerField(default="100000")

    def __str__(self):
        return self.trash_path

trashes/forms.py
import os
from django import forms
from models import Trash


class TrashForm(forms.ModelForm):
    class Meta:
        model = Trash
        fields = ["trash_path", "max_trash_size", "max_file_size",
                  "max_file_time"]

trashes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from .models import Trash
from .forms import TrashForm
import shutil
import sys
import os
sys.path.insert(0, '/usr/local/lib/python2.7/dist-packages/lab2-1.0-py2.7.egg')
import smart_rm


def list(request):
    trashes = Trash.objects.all()
    for trash in trashes:
        trash.free_space = smart_rm.remove.RemoveCommand(
                                                trash_path=trash.trash_path,
                                                size=trash.max_trash_size
                                                ).find_free_space()
    return render(request, 'trashes/list.html', {'trashes': trashes})


def create(request):
    form = TrashForm(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        trash = form.save()
        smart_rm.my_trash.create_trash_dir(trash.trash_path)
        return redirect('trashes:list')
    return render(request, 'trashes/new.html', {'form': form})


def update(request, id):
    trash = get_object_or_404(Trash, id=id)
    form = TrashForm(request.POST or None, instance=trash)
    old_path = os.path.abspath(trash.trash_path)
    if form.is_valid() and request.method == 'POST':
        trash = form.save()
        new_path = os.path.abspath(trash.trash_path)
        if new_path != old_path:
            os.renames(old_path, new_path)
        return redirect('trashes:list')
    return render(request, 'trashes/update.html',
                  {'trash_id': id, 'form': form})


def delete(request, id):
    trash = get_object_or_404(Trash, id=id)
    if request.method == 'POST':
        if os.path.exists(trash.trash_path):
            shutil.rmtree(trash.trash_path)
        trash.delete()
    return redirect('trashes:list')


def detail(request, id):
    trash = get_object_or_404(Trash, id=id)
    trash_obj = smart_rm.my_trash.Trash(trash_path=trash.trash_path,
                                        max_file_size=trash.max_file_size,
                                        max_file_time=trash.max_file_time,
                                        max_trash_size=trash.max_trash_size
                                        )
    trash_list = trash_obj.show()
    return render(request, "trashes/detail.html",
                  {'trash_list': trash_list, 'trash_id': id, })


def restore(request, id):
    trash = get_object_or_404(Trash, id=id)
    if request.method == 'POST':
        name = request.POST['file_name']
        smart_rm.restore.RestoreCommand(trash_path=trash.trash_path
                                        ).run([name])
    return redirect(request.META.get('HTTP_REFERER'))


def clear(request, id):
    trash = get_object_or_404(Trash, id=id)
    if request.method == 'POST':
        name = request.POST['file_name']
        smart_rm.clear.ClearCommand(trash_path=trash.trash_path).run([name])
    return redirect(request.META.get('HTTP_REFERER'))

templates/trashes/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1 class="page-header">FILES IN TRASH</h1>
            <table class="table table-striped table-hover">
                <thead>
                  <tr class="success">
                    <td>FILE NAME</td>
                    <td>ORIGINAL LOCATION</td>
                    <td>SIZE</td>
                    <td>TYPE</td>
                    <td>DELETION DATE</td>
                    <td>STATE</td>
                    <td></td>
                  </tr>
                </thead>
                <tbody>
                    {% for obj in trash_list %}
                        <tr>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.original_location }}</td>
                            <td>{{ obj.size|filesizeformat }}</td>
                            <td>{{ obj.type }}</td>
                            <td>{{ obj.deletion_date }}</td>
                            <td>{{ obj.state }}</td>
                            <td>
                                <div style="display: flex;">
                                    <form method="post", action="{% url 'trashes:restore' id=trash_id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="file_name" value="{{ obj.name}}">
                                        <button type="submit" class="save btn btn-success"><span class="glyphicon glyphicon-thumbs-up"></button>
                                    </form>
                                    <form method="post", action="{% url 'trashes:clear' id=trash_id %}">
                                        {% csrf_token %}
                                        <input type="hidden" name="file_name" value="{{ obj.name }}">
                                        <button type="submit" class="save btn btn-primary"><span class="glyphicon glyphicon-thumbs-down"></button>
                                    </form>
                                </div>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="7" class="text-center bg-defaulte">
                                <small>No files</small>
                            </td>
                        <tr>
                    {% endfor %}
                    <form method="post", action="{% url 'trashes:restore' id=trash_id %}">
                        {% csrf_token %}
                        <input type="hidden" name="file_name" value="">
                        <button type="submit" class="save btn btn-success"><span class="glyphicon glyphicon-thumbs-up"></button>
                    </form>
                    <form method="post", action="{% url 'trashes:clear' id=trash_id %}">
                        {% csrf_token %}
                        <input type="hidden" name="file_name" value="">
                        <button type="submit" class="save btn btn-primary"><span class="glyphicon glyphicon-thumbs-down"></button>
                    </form>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/trashes/list.html
{% extends 'base.html' %}

  {% block content %}

    <div class="container">
      <div class="jumbotron">
        <h1 class="page-header">TRASHES</h1>

        <table class="table table-striped table-hover">
          <thead>
            <tr class="success">
            <td>TRASH NAME</td>
            <td>TOTAL SPACE</td>
            <td>FREE SPACE</td>
            <td>MAX FILE SIZE</td>
            <td>MAX FILE TIME</td>
            <td></td>
            </tr>
          </thead>

          <tbody>
            {% for trash in trashes %}

              <tr>
                <td><a href="{% url 'trashes:detail' id=trash.id %}">
                  {{ trash.trash_path }}</a></td>

                <td>{{ trash.max_trash_size|filesizeformat }}</td>

                <td>{{ trash.free_space|filesizeformat }}</td>

                <td>{{ trash.max_file_size|filesizeformat }}</td>

                <td>{{ trash.max_file_time }}</td>

                <td>
                  <div style="display: flex;">
                    <a href="{% url 'trashes:update' id=trash.id %}" class="save btn btn-success">
                      <span class="glyphicon glyphicon-pencil"></a>

                    <form method="post" action="{% url 'trashes:delete' id=trash.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></button>
                    </form>
                  </div>
                </td>
              </tr>

            {% endfor %}
          </tbody>

        </table><br/>

        <a href="{% url 'trashes:create' %}" ><span class="glyphicon glyphicon-plus"></span></a>
      </div>
    </div>

  {% endblock %}

templates/trashes/new.html
{% extends 'base.html' %}

  {% block content %}
    <div class="container">
      <div class="jumbotron">
      <div class="page-header">
        <h1>CREATE NEW TRASH</h1>
      </div>

      <form action="{% url 'trashes:create' %}" method="POST" class="form-horizontal">
        <fieldset>
        <div class="fieldWrapper" class="form-group">
        <p><label for="id_trash_path" class="col-lg-3 control-label">Trash path:</label>
          <div class="col-lg-7">
          <input class="form-control" type="text" name="trash_path" placeholder="~/.local/share/my_trash"
            value="{{form.trash_path.value}}" required id="id_trash_path" maxlength="200" />
          </div></p></div><br></br>
        <div class="fieldWrapper" class="form-group">
        <p><label for="id_max_file_size" class="col-lg-3 control-label">Max file size:</label>
          <div class="col-lg-7">
           <input class="form-control" type="text" name="max_file_size" placeholder="10"
           value="{{form.max_file_size.value}}" required id="id_max_file_size" maxlength="10" />
         </div></p></div><br></br>
        <div class="fieldWrapper" class="form-group">
        <p><label for="id_max_file_time" class="col-lg-3 control-label">Max file time:</label>
          <div class="col-lg-7">
           <input class="form-control" type="text" name="max_file_time" placeholder="3"
           value="{{form.max_file_time.value}}" required id="id_max_file_time" maxlength="10" />
         </div></p></div><br></br>
         <div class="fieldWrapper" class="form-group">
         <p><label for="id_max_trash_size" class="col-lg-3 control-label">Max trash size:</label>
           <div class="col-lg-7">
            <input class="form-control" type="text" name="max_trash_size" placeholder="1000"
             value="{{form.max_trash_size.value}}" required id="id_max_trash_size" maxlength="10" />
          </div></p></div><br></br>
       </fieldset>
        {% csrf_token %}
        <br></br>
        <div class="col-lg-3 control-label">
        <button type="submit" class="save btn btn-default">OK</button></div>
      </form>
      </div>
    </div>
  {% endblock %}

templates/trashes/update.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <div style="display: flex; justify-content: space-between;">
        <h1 class="page-header">CHANGE TRASH</h1>
      </div>
      <form action="{% url 'trashes:update' id=trash_id %}" method="POST" class="post-horizontal">
        <fieldset>

        <div class="fieldWrapper" class="form-group">
        <p><label for="id_trash_path" class="col-lg-3 control-label">Trash path:</label>
          <div class="col-lg-7">
          <input class="form-control" type="text" name="trash_path" value="{{form.trash_path.value}}"
            required id="id_trash_path" maxlength="200" />
          </div></p></div><br></br>
        <div class="fieldWrapper" class="form-group">
        <p><label for="id_max_file_size" class="col-lg-3 control-label">Max file size:</label>
          <div class="col-lg-7">
           <input class="form-control" type="text" name="max_file_size" value="{{form.max_file_size.value}}"
           required id="id_max_file_size" maxlength="10" />
         </div></p></div><br></br>
        <div class="fieldWrapper" class="form-group">
        <p><label for="id_max_file_time" class="col-lg-3 control-label">Max file time:</label>
          <div class="col-lg-7">
           <input class="form-control" type="text" name="max_file_time" value="{{form.max_file_time.value}}"
           required id="id_max_file_time" maxlength="10" />
         </div></p></div><br></br>
         <div class="fieldWrapper" class="form-group">
         <p><label for="id_max_trash_size" class="col-lg-3 control-label">Max trash size:</label>
           <div class="col-lg-7">
            <input class="form-control" type="text" name="max_trash_size" value="{{form.max_trash_size.value}}"
            required id="id_max_trash_size" maxlength="10" />
          </div></p></div><br></br>
       </fieldset>
        {% csrf_token %}
        <br></br>
        <div class="col-lg-3 control-label">
        <input name="submit" value="OK" type="submit" class="save btn btn-success">
        </input>

      </div>
      </form>

      <form method="post" action="{% url 'trashes:delete' id=trash_id %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></button>
      </form>
    </div>
  </div>
{% endblock %}