home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^trashes/', include('trashes.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.conf.urls import url

from . import views

app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/$', views.create, name='create'),
    url(r'^update/(?P<id>\d+?)$', views.update, name='update'),
    url(r'^delete/(?P<id>\d+?)$', views.delete, name='delete'),
    url(r'^detail/(?P<id>\d+?)$', views.detail, name='detail'),
    url(r'^detail/(?P<id>\d+?)/tree(?P<path>.*)$', views.get_files, name='get_files'),
    url(r'^detail/(?P<id>\d+?)/execute$', views.execute, name='execute'),
    url(r'^add_file_to_task/(?P<id>\d+?)$', views.add_file_to_task, name='add_file_to_task'),
    url(r'^remove_file_from_task/(?P<id>\d+?)$', views.remove_file_from_task, name='remove_file_from_task'),
    url(r'^add_by_regex/(?P<id>\d+?)$', views.add_by_regex, name='add_by_regex')
]

trashes/urls.py
from django.conf.urls import url

from . import views

app_name = 'trashes'
urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/$', views.create, name='create'),
    url(r'^update/(?P<id>\d+?)$', views.update, name='update'),
    url(r'^delete/(?P<id>\d+?)$', views.delete, name='delete'),
    url(r'^detail/(?P<id>\d+?)$', views.detail, name='detail'),
    url(r'^restore/(?P<id>\d+?)$', views.restore, name='restore'),
    url(r'^clear/(?P<id>\d+?)$', views.clear, name='clear'),
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'home.html')

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <title>smart_rm_app</title>

  	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type = "text/css"/>
  </head>

  <body>
  	<nav class="navbar navbar-inverse">
  	<div class="container-fluid">
  		<ul class="nav navbar-nav">
  			<li><a href="{% url 'home' %}">Home</a></li>
  			<li><a href="{% url 'trashes:list' %}">Trashes</a></li>
  			<li><a href="{% url 'tasks:list' %}">Tasks</a></li>
  		</ul>
  	</div>
  	</nav>

  	<div class="content">
  	   {% block content %}
  	   {% endblock %}
  	</div>
  </body>

</html>

templates/home.html
{% extends "base.html"%}
{% block content %}
<div class="container">

  <div class="jumbotron">
    <div class="container-fluid">
      <h1 class="page-header">SMART RM APPLICATION</h1>
      <p><blockquote>This is the web interface of the utility <em>smart_rm</em>, which supports the:
      <ul><font size="4">
        <li> View known trashes (list, separate trash in detail);</li>
        <li> Creation, change modifications and delete trashes;</li>
        <li> View tasks (list, separate task in details);</li>
        <li> Creation, managment and display the status of tasks.</li>
        </font>
      </ul></blockquote>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <div class="jumbotron">
        <h2>Trashes</h2>
        <p><blockquote>Trash's characteristics:
            <ul>
              <li>Trash path</li>
              <li>Max size of basket</li>
              <li>Max file size to keep in</li>
              <li>Max time to keep files in</li>
            </ul></blockquote>
        </p>
        <p><a class="btn btn-success" href="{% url 'trashes:create' %}" role="button">Create trash &raquo;</a></p>
      </div>
    </div>

    <div class="col-md-6">
      <div class="jumbotron">
        <h2>Tasks</h2>
        <p><blockquote>Task's characteristics:
            <ul>
              <li>Task name</li>
              <li>Trash path</li>
              <li>Regex</li>
            </ul></blockquote>
        </p>
        <br>
        <p><a class="btn btn-success" href="{% url 'tasks:list' %}" role="button">View known tasks &raquo;</a></p>
      </div>
    </div>
  </div>



</div>
{% endblock %}