home/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home, name='home'),
]

myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('home.urls')),
    url(r'^trashes/', include('trashes.urls')),
    url(r'^tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.conf.urls import url

from . import views

app_name = 'tasks'
urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new/$', views.create, name='create'),
    url(r'^update/(?P<id>\d+?)$', views.update, name='update'),
    url(r'^delete/(?P<id>\d+?)$', views.delete, name='delete'),
    url(r'^detail/(?P<id>\d+?)$', views.detail, name='detail'),
    url(r'^detail/(?P<id>\d+?)/tree(?P<path>.*)$', views.get_files, name='get_files'),
    url(r'^detail/(?P<id>\d+?)/execute$', views.execute, name='execute'),
    url(r'^add_file_to_task/(?P<id>\d+?)$', views.add_file_to_task, name='add_file_to_task'),
    url(r'^remove_file_from_task/(?P<id>\d+?)$', views.remove_file_from_task, name='remove_file_from_task'),
    url(r'^add_by_regex/(?P<id>\d+?)$', views.add_by_regex, name='add_by_regex')
]

tasks/models.py
from __future__ import unicode_literals

from django.db import models
from trashes.models import Trash

# Create your models here.


class Task(models.Model):
    """model for task"""

    name = models.CharField(max_length=50)
    trash = models.ForeignKey(Trash, on_delete=models.CASCADE,
                              related_name='tasks')
    is_dry_run = models.BooleanField(default=False)

    executed = models.BooleanField(default=False)

    def file_paths(self):
        return [el.path for el in self.files.all()]

    def __str__(self):
        return self.name


class File(models.Model):
    INIT_STATUS = 0
    REMOVED_STATUS = 1
    ERROR_STATUS = 2
    DRY_RUN = 3
    STATUS_CHOICES = (
        (INIT_STATUS, 'Init'),
        (REMOVED_STATUS, 'Complete'),
        (ERROR_STATUS, 'ERROR'),
        (DRY_RUN, 'Dry_Run'),
    )

    path = models.CharField(max_length=200)
    task = models.ForeignKey(Task, on_delete=models.CASCADE,
                             related_name="files",)
    status = models.IntegerField(choices=STATUS_CHOICES, default=INIT_STATUS)
    error_message = models.CharField(max_length=1000, default='')

    @property
    def status_name(self):
        return self.STATUS_CHOICES[self.status][1]

    def __str__(self):
        return "File: id:{0}, path: {1}".format(self.id, self.path)

    class Meta:
        unique_together = ('path', 'task')

tasks/forms.py
from django import forms
from tasks.models import Task


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ["name", "trash", "is_dry_run"]

tasks/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import Task, File
from .forms import TaskForm
import os
from helper import FileObject
import smart_rm
import datetime
from smart_rm.my_rm.common_functions import RemoveMethods


def list(request):
    tasks = Task.objects.all()
    return render(request, 'tasks/list.html', {'tasks': tasks})


def create(request):
    form = TaskForm(request.POST or None)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('tasks:list')
    return render(request, 'tasks/new.html', {'form': form})


def update(request, id):
    task = get_object_or_404(Task, id=id)
    form = TaskForm(request.POST or None, instance=task)
    if form.is_valid() and request.method == 'POST':
        form.save()
        return redirect('tasks:list')
    return render(request, 'tasks/update.html', {'form': form, 'task': task})


def delete(request, id):
    task = get_object_or_404(Task, id=id)
    if request.method == 'POST':
        task.delete()
        return redirect('tasks:list')


def detail(request, id):
    task = get_object_or_404(Task, id=id)
    files = task.files.all()
    return render(request, 'tasks/detail.html',
                  {'files': files, 'task_id': id})


def get_files(request, id, path):
    FILES_PER_PAGE = 10
    path = path if path else os.path.expanduser('~')
    items = dict()
    try:
        files = os.listdir(path)
        items = map(lambda filename: FileObject(path, filename, id), files)
        paginator = Paginator(items, FILES_PER_PAGE)
        page = request.GET.get('page')

        try:
            items = paginator.page(page)
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)

        return render(request, 'tasks/get_files.html',
                      {'items': items, 'task_id': id,
                       'paginator': paginator, 'current_dir': path})
    except Exception:
        return render(request, 'tasks/error_page.html')


def add_file_to_task(request, id):
    task = get_object_or_404(Task, id=id)
    if request.method == 'POST':
        path = request.POST['path']
        try:
            File.objects.create(path=path, task=task)
        except Exception:
            pass
    return redirect(request.META.get('HTTP_REFERER'))


def remove_file_from_task(request, id):
    task = get_object_or_404(Task, id=id)
    if request.method == 'POST':
        path = request.POST['path']
        file = task.files.filter(path=path).first()
        if file:
            file.delete()
    return redirect(request.META.get('HTTP_REFERER'))


def add_by_regex(request, id):
    task = get_object_or_404(Task, id=id)
    if request.method == 'POST':
        data = request.POST
        files = smart_rm.my_rm.common_functions.get_files_by_regex(
            data['regex'], [data['directory']])
        for file in files:
            File.objects.create(path=file, task=task)
        return redirect('tasks:detail', id=task.id)
    else:
        return render(request, 'tasks/regexp_task.html', {'task_id': id})


def execute(request, id):
    task = get_object_or_404(Task, id=id)
    task_files = task.file_paths()
    trash = task.trash
    if task.is_dry_run:
        is_dry_run = True
    else:
        is_dry_run = False
    smart_rm.clear.ClearCommand(trash_path=trash.trash_path,
                                is_dry_run=is_dry_run
                                ).delete_by_size_date(value_date=datetime.timedelta(seconds=trash.max_file_time))
    trashed_files = smart_rm.remove.RemoveCommand(trash_path=trash.trash_path,
                                                  max_file_size=trash.max_file_size,
                                                  size=trash.max_trash_size,
                                                  remove_method=RemoveMethods.RECURSIVE_MODE,
                                                  is_dry_run=is_dry_run
                                                  ).run(task_files)
    task.executed = True
    task.save()

    for trashed_file in trashed_files:
        file_model = task.files.get(path=trashed_file.original_location)
        if trashed_file.state == "OK":
            file_model.status = File.REMOVED_STATUS
            file_model.error_message = ''
        elif trashed_file.state == "DRY_RUN":
            file_model.status = File.DRY_RUN
        else:
            file_model.status = File.ERROR_STATUS
            file_model.error_message = trashed_file.error_message
        file_model.save()

    return redirect('tasks:list')

templates/tasks/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
        <div style="display: flex; justify-content: space-between;">
            <h1 class="page-header">TASK DETAIL</h1>

        </div>
        <table class="table table-striped table-hover">
            <thead>
              <tr class="success">
                <td>FILE NAME</td>
                <td>COMMENTS</td>
                <td>STATUS</td>
              </tr>
            </thead>
            <tbody>
                {% for file in files %}
                    <tr>
                        <td>{{ file.path }}</td>
                        {% if file.error_message %}
                          <td>{{ file.error_message }}</td>
                        {% else %}
                          <td></td>
                        {% endif %}
                        <td>{{ file.status_name }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6" class="text-center bg-defaulte">
                            <small>No files</small>
                        </td>
                    <tr>
                {% endfor %}
            </tbody>
        </table>
          <div>
              <form method="post"  style = "float: left" action="{% url 'tasks:execute' id=task_id %}">
                  {% csrf_token %}
                  <button type="submit" class="btn btn-success">
                      <span class="glyphicon glyphicon-play"></span>
                  </button>
              </form> &ensp;&nbsp;
              <a style = "float: left" class="btn btn-info" href="{% url 'tasks:get_files' id=task_id path='' %}">Add files</a>
              <a style = "float: left" class="btn btn-primary" href="{% url 'tasks:add_by_regex' id=task_id %}">Add files by regex</a>
          </div>
        </div>
    </div>
{% endblock %}

templates/tasks/error_page.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>PERMISSION DENIDED</h1>
    </div>
  </div>
{% endblock %}

templates/tasks/get_files.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        {% for item in items %}
          <div class="col-md-12" style="border-bottom: 1px solid #ddd; padding: 5px 0; display: flex; justify-content: space-between;">
            <div>
              {% if item.is_dir %}
                <span class="glyphicon glyphicon-folder-close" aria-hidden="true"></span>&nbsp;
                <a href="{% url 'tasks:get_files' id=task_id path=item.path %}">
                    {{ item.name }}
                </a>
              {% else %}
                <div class="col-md-12" style="padding: 5px 0">
                  <span class="glyphicon glyphicon-file" aria-hidden="true"></span>&nbsp; {{ item.name }}
                </div>
              {% endif %}
            </div>
            <div>
              {% if item.belongs_to_task %}
                <form method="post", action="{% url 'tasks:remove_file_from_task' id=task_id %}">
                {% csrf_token %}
                  <input type="hidden" name="path" value="{{ item.path }}">
                  <button type="submit" class="btn btn-default">remove from task</button>
                </form>
              {% else %}
                <form method="post", action="{% url 'tasks:add_file_to_task' id=task_id %}">
                {% csrf_token %}
                  <input type="hidden" name="path" value="{{ item.path }}">
                  <button type="submit" class="btn btn-default">add to task</button>
                </form>
              {% endif %}
            </div>
          </div>
        {% endfor %}

        <ul class="pagination nav navbar-nav">
            {% for page in paginator.page_range %}
                <li class="{% if items.number == page  %}active{% endif %}"><a href="?page={{ page }}">{{ page }}</a></li>
            {% endfor %}
         </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/tasks/list.html
{% extends 'base.html' %}

  {% block content %}

    <div class="container">
      <div class="jumbotron">
        <h1 class="page-header">TASKS</h1>

        <table class="table table-striped table-hover">
          <thead>
            <tr class="success">
            <td>TASK NAME</td>
            <td>TRASH</td>
            <td>EXECUTED</td>
            <td></td>
            </tr>
          </thead>

          <tbody>
            {% for task in tasks %}

              <tr>
                <td><a href="{% url 'tasks:detail' id=task.id %}">
                  {{ task.name }}</a></td>

                <td>{{ task.trash.trash_path }}</td>
                
                <td>
                  {% if task.executed %}
                    <span class="glyphicon glyphicon-ok"></span>
                  {% else %}
                    <span class="glyphicon glyphicon-remove"></span>
                  {% endif %}
                </td>

                <td>
                  <div style="display: flex;">
                    <a href="{% url 'tasks:update' id=task.id %}" class="save btn btn-success">
                      <span class="glyphicon glyphicon-pencil"></a>

                    <form method="post" action="{% url 'tasks:delete' id=task.id %}">
                      {% csrf_token %}
                      <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></button>
                    </form>
                     <form method="post" action="{% url 'tasks:execute' id=task.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-warning"><span class="glyphicon glyphicon-play"></span></button>
                    </form>
                  </div>
                  {# <a href="/smart_rm_app/trashes/delete/{{ trash.id }}"> #}
                    {# <span class="glyphicon glyphicon-trash"></a> #}
                </td>
              </tr>

            {% endfor %}
          </tbody>

        </table><br/>

        <a href="{% url 'tasks:create' %}" ><span class="glyphicon glyphicon-plus"></span></a>
      </div>
    </div>

  {% endblock %}

templates/tasks/new.html
{% extends 'base.html' %}
  {% block content %}
    <div class="container">
      <div class="jumbotron">
        <h1 class="page-header">CREATE NEW TASK</h1>
         <form action="{% url 'tasks:create' %}" method="post" style="form-horizontal">
           <fieldset>

            {{ form.as_p }}

          </fieldset>
          {% csrf_token %}
          <br></br>
          <div class="col-lg-2 control-label">
          <input type="submit" name="submit" value="OK"
            class="btn btn-default"></input></div>

          </form>
      </div>
    </div>
{% endblock %}

templates/tasks/regexp_task.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <div style="display: flex; justify-content: space-between;">
      <h1 class="page-header">ADD REGEX TASK</h1>
    </div>
    <form method="post" action={% url 'tasks:add_by_regex' id=task_id %} class="form-horizontal">
        {% csrf_token %}
        <div class="fieldWrapper" class="form-group">
        <p><label for="regex" class="col-lg-3 control-label">Regular expression:</label>
          <div class="col-lg-7">
          <input class="form-control" type="text" name="regex" holdplacer="test"
            required id="regex" maxlength="100" />
          </div></p></div><br></br>
        <div class="fieldWrapper" class="form-group">
        <p><label for="directory" class="col-lg-3 control-label">Directory:</label>
          <div class="col-lg-7">
          <input class="form-control" type="text" name="directory" holdplacer="/home/ana"
            required id="directory" maxlength="100" />
          </div></p></div><br></br>
          </<br></br>
          <div class="col-lg-3 control-label">
              <button type="submit" class="btn btn-success" style="margin-top:10px;">Create task</button>
          </div>
          </<br></br>
    </form>
    </div>
  </div>
{% endblock %}

templates/tasks/update.html
{% extends 'base.html' %}
  {% block content %}
    <div class="container">
      <div class="jumbotron">
        <div style="display: flex; justify-content: space-between;">
          <h1 class="page-header">CHANGE TASK "{{ task.name }}"</h1>

        </div>
        <form action="{% url 'tasks:update' id=task.id %}" method="post" style="form-horizontal">
           <fieldset>
            {{ form.as_p }}

          </fieldset>
          {% csrf_token %}
          <br></br>
          <div class="col-lg-2 control-label">
          <input type="submit" name="submit" value="OK"
            class="btn btn-default"></input></div>

        </form>
        <form method="post" action="{% url 'tasks:delete' id=task.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-trash"></button>
        </form>
      </div>
    </div>
{% endblock %}